### ISSUE TITLE
FJSP

### ISSUE THREAD

**Issue by beckhz** [zcaicaros/L2D#9]
Hi，
Me again![521cc9d3-92f9-40bc-af2d-f5309211229d](https://user-images.githubusercontent.com/13513093/172286346-4806ba01-f111-41a6-a402-9acc912b4aca.png)
Your paper is very good, but the problem of dynamic flexible shop scheduling is very common in actual production practice. How can this problem be improved based on your paper?

**Comment by zcaicaros** [comment]
Hi,

Based on my understanding, it is more suitable for modeling the dynamic job shop scheduling as an event-driven environment since the dynamic events such as new job arrival, machine breakdown, etc., are happening on the fly. You can refer to the following three papers for some hints:
 1. https://arxiv.org/abs/2106.03051
 2. https://arxiv.org/pdf/2201.00548.pdf
 3. https://arxiv.org/abs/2106.01086

The straightforward idea is to incorporate the flexible machines and dynamic events into these environments and design a DRL agent to solve them (the second paper follows this idea).

As for my code, I can not see an easy way to introduce these features.

If you are interested in this topic, maybe we can discuss it further to see if we can collaborate.

Regards,
Cong

**Comment by beckhz** [comment]
great! Can't wait to read these papers! And looking forward to working with you

**Comment by free001a** [comment]
> Hi， Me again![521cc9d3-92f9-40bc-af2d-f5309211229d](https://user-images.githubusercontent.com/13513093/172286346-4806ba01-f111-41a6-a402-9acc912b4aca.png) Your paper is very good, but the problem of dynamic flexible shop scheduling is very common in actual production practice. How can this problem be improved based on your paper?

Hello, sorry to interrupt, this may be a violation of community etiquette, but I have no choice, please forgive me. I am very interested in this paper and the code, but there are some questions that nobody can ask and discuss, and I am struggling to solve them. I really hope to get others' advice. May I exchange my contact information with you, please?

Or do you think this is a violation of your privacy? I wrote my confusion in the latest issue, hoping to get some advice.

Thank you so much!
